In [2]:
#Working with nav_history.csv dataset.
import pandas as pd

In [3]:
nav_history = pd.read_csv("../data/raw/02_nav_history.csv")

In [4]:
nav_history.head()

   amfi_code        date      nav
0     119551  2022-01-03  54.3856
1     119551  2022-01-04  54.3474
2     119551  2022-01-05  54.6869
3     119551  2022-01-06  55.4550
4     119551  2022-01-07  55.3692

In [5]:
nav_history.info()

<class 'pandas.DataFrame'>
RangeIndex: 46000 entries, 0 to 45999
Data columns (total 3 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   amfi_code  46000 non-null  int64
 1   date       46000 non-null  str
 2   nav        46000 non-null  float64
dtypes: float64(1), int64(1), str(1)
memory usage: 1.1 MB

In [6]:
#missing values
nav_history.isnull().sum()

amfi_code    0
date         0
nav          0
dtype: int64

In [7]:
#checking for duplicates
nav_history.duplicated().sum()

np.int64(0)

In [8]:
#invlid NAV values
(nav_history['nav'] <= 0).sum()

np.int64(0)

In [9]:
#parse dates to datetime
nav_history['date'] = pd.to_datetime(
    nav_history['date']
)

In [10]:
nav_history = nav_history.sort_values(
    ['amfi_code', 'date']
)

In [11]:
#Forward-fill missing NAV values
nav_history['nav'] = (
    nav_history
    .groupby('amfi_code')['nav']
    .ffill()
)

In [19]:
nav_history = nav_history.drop_duplicates()
nav_history = nav_history[
    nav_history['nav'] > 0
]

In [20]:
nav_history.duplicated().sum()
#Actually,there are no duplicates before and after performing drop_duplicates()function too.

np.int64(0)

In [21]:
nav_history.info()

<class 'pandas.DataFrame'>
Index: 46000 entries, 5750 to 45999
Data columns (total 3 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   amfi_code  46000 non-null  int64
 1   date       46000 non-null  datetime64[us]
 2   nav        46000 non-null  float64
dtypes: datetime64[us](1), float64(1), int64(1)
memory usage: 1.4 MB

In [23]:
nav_history = nav_history.reset_index(drop=True)

In [24]:
nav_history.info()

<class 'pandas.DataFrame'>
RangeIndex: 46000 entries, 0 to 45999
Data columns (total 3 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   amfi_code  46000 non-null  int64
 1   date       46000 non-null  datetime64[us]
 2   nav        46000 non-null  float64
dtypes: datetime64[us](1), float64(1), int64(1)
memory usage: 1.1 MB

In [27]:
#NAV_dataset.csv is cleaned
nav_history.to_csv(
    "../data/processed/nav_history_cleaned.csv",
    index=False
)

In [29]:
#Working with investor_transactions.csv dataset.
transactions = pd.read_csv(
    "../data/raw/08_investor_transactions.csv"
)

In [30]:
transactions.head()

,investor_id,transaction_date,amfi_code,transaction_type,amount_inr,state,city,city_tier,age_group,gender,annual_income_lakh,payment_mode,kyc_status
0,INV003054,2024-01-01,119092,SIP,1834,Telangana,Hyderabad,T30,56+,Female,77.1,UPI,Verified
1,INV002952,2024-01-01,148567,Redemption,392882,Punjab,Amritsar,B30,18-25,Male,7.1,Cheque,Verified
2,INV003420,2024-01-01,118636,SIP,912,Haryana,Faridabad,B30,36-45,Male,47.2,Mandate,Verified
3,INV003436,2024-01-01,118634,SIP,1102,Maharashtra,Mumbai,T30,36-45,Female,54.4,Cheque,Pending
4,INV004691,2024-01-01,119094,Lumpsum,8682,Delhi,Noida,T30,26-35,Male,14.5,Net Banking,Pending

In [31]:
transactions.head(10)

,investor_id,transaction_date,amfi_code,transaction_type,amount_inr,state,city,city_tier,age_group,gender,annual_income_lakh,payment_mode,kyc_status
0,INV003054,2024-01-01,119092,SIP,1834,Telangana,Hyderabad,T30,56+,Female,77.1,UPI,Verified
1,INV002952,2024-01-01,148567,Redemption,392882,Punjab,Amritsar,B30,18-25,Male,7.1,Cheque,Verified
2,INV003420,2024-01-01,118636,SIP,912,Haryana,Faridabad,B30,36-45,Male,47.2,Mandate,Verified
3,INV003436,2024-01-01,118634,SIP,1102,Maharashtra,Mumbai,T30,36-45,Female,54.4,Cheque,Pending
4,INV004691,2024-01-01,119094,Lumpsum,8682,Delhi,Noida,T30,26-35,Male,14.5,Net Banking,Pending
5,INV001497,2024-01-01,101208,SIP,3295,Maharashtra,Mumbai,T30,36-45,Male,56.8,Mandate,Verified
6,INV000786,2024-01-01,101208,SIP,15047,Madhya Pradesh,Bhopal,B30,26-35,Male,17.9,Mandate,Verified
7,INV000616,2024-01-01,100016,SIP,933,Maharashtra,Nashik,B30,36-45,Male,50.4,Mandate,Verified
8,INV003670,2024-01-01,119120,SIP,10672,Punjab,Chandigarh,T30,36-45,Male,38.4,Net Banking,Verified
9,INV002054,2024-01-01,148567,SIP,1111,Telangana,Hyderabad,T30,26-35,Male,17.8,Net Banking,Verified

In [32]:
transactions.tail(10)

,investor_id,transaction_date,amfi_code,transaction_type,amount_inr,state,city,city_tier,age_group,gender,annual_income_lakh,payment_mode,kyc_status
32768,INV004993,2025-05-30,149322,Lumpsum,84982,Karnataka,Bangalore,T30,36-45,Female,55.6,Net Banking,Verified
32769,INV001154,2025-05-30,102885,SIP,2051,Delhi,Noida,T30,36-45,Female,34.8,UPI,Verified
32770,INV000734,2025-05-30,149322,Lumpsum,127218,Maharashtra,Pune,T30,26-35,Female,15.2,Mandate,Verified
32771,INV002074,2025-05-30,118633,SIP,2383,Karnataka,Bangalore,T30,26-35,Female,6.1,UPI,Verified
32772,INV000339,2025-05-30,148569,SIP,1109,Uttar Pradesh,Kanpur,B30,26-35,Male,22.3,Cheque,Verified
32773,INV003340,2025-05-30,101207,Lumpsum,168029,Madhya Pradesh,Indore,T30,26-35,Male,22.5,Net Banking,Verified
32774,INV001838,2025-05-30,119093,SIP,2175,Uttar Pradesh,Kanpur,B30,46-55,Male,27.6,Mandate,Verified
32775,INV000074,2025-05-30,120504,SIP,25998,Rajasthan,Jaipur,T30,26-35,Female,8.4,UPI,Verified
32776,INV002929,2025-05-30,148568,SIP,459,West Bengal,Kolkata,T30,26-35,Male,13.0,Mandate,Verified
32777,INV001852,2025-05-30,118633,Redemption,226721,Telangana,Hyderabad,T30,26-35,Male,21.7,Cheque,Verified

In [33]:
transactions.info()

<class 'pandas.DataFrame'>
RangeIndex: 32778 entries, 0 to 32777
Data columns (total 13 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   investor_id         32778 non-null  str
 1   transaction_date    32778 non-null  str
 2   amfi_code           32778 non-null  int64
 3   transaction_type    32778 non-null  str
 4   amount_inr          32778 non-null  int64
 5   state               32778 non-null  str
 6   city                32778 non-null  str
 7   city_tier           32778 non-null  str
 8   age_group           32778 non-null  str
 9   gender              32778 non-null  str
 10  annual_income_lakh  32778 non-null  float64
 11  payment_mode        32778 non-null  str
 12  kyc_status          32778 non-null  str
dtypes: float64(1), int64(2), str(10)
memory usage: 3.3 MB

In [34]:
transactions.columns

Index(['investor_id', 'transaction_date', 'amfi_code', 'transaction_type',
       'amount_inr', 'state', 'city', 'city_tier', 'age_group', 'gender',
       'annual_income_lakh', 'payment_mode', 'kyc_status'],
      dtype='str')

In [35]:
#Missing values
transactions.isnull().sum()

investor_id           0
transaction_date      0
amfi_code             0
transaction_type      0
amount_inr            0
state                 0
city                  0
city_tier             0
age_group             0
gender                0
annual_income_lakh    0
payment_mode          0
kyc_status            0
dtype: int64

In [40]:
#checking for duplicates
transactions.duplicated().sum()

np.int64(0)

In [41]:
#Checking transaction types
transactions['transaction_type'].unique()

<StringArray>
['SIP', 'Redemption', 'Lumpsum']
Length: 3, dtype: str

In [42]:
#Checking for KYC values
transactions['kyc_status'].unique()

<StringArray>
['Verified', 'Pending']
Length: 2, dtype: str

In [43]:
#All transaction amounts are valid
(transactions['amount_inr'] <= 0).sum()
print("Duplicates:", transactions.duplicated().sum())
print("Invalid amounts:", (transactions['amount_inr'] <= 0).sum())

Duplicates: 0
Invalid amounts: 0

In [44]:
#Parse dates to datetime
transactions['transaction_date'] = pd.to_datetime(
    transactions['transaction_date']
)

In [45]:
transactions.info()

<class 'pandas.DataFrame'>
RangeIndex: 32778 entries, 0 to 32777
Data columns (total 13 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   investor_id         32778 non-null  str
 1   transaction_date    32778 non-null  datetime64[us]
 2   amfi_code           32778 non-null  int64
 3   transaction_type    32778 non-null  str
 4   amount_inr          32778 non-null  int64
 5   state               32778 non-null  str
 6   city                32778 non-null  str
 7   city_tier           32778 non-null  str
 8   age_group           32778 non-null  str
 9   gender              32778 non-null  str
 10  annual_income_lakh  32778 non-null  float64
 11  payment_mode        32778 non-null  str
 12  kyc_status          32778 non-null  str
dtypes: datetime64[us](1), float64(1), int64(2), str(9)
memory usage: 3.3 MB

In [46]:
#Investor_transactions.csv datset is cleaned.
transactions.to_csv(
    "../data/processed/investor_transactions_cleaned.csv",
    index=False
)

In [47]:
#Working with scheme_performance.csv dataset.
performance = pd.read_csv(
    "../data/raw/07_scheme_performance.csv"
)

In [48]:
performance.head()

,amfi_code,scheme_name,fund_house,category,plan,return_1yr_pct,return_3yr_pct,return_5yr_pct,benchmark_3yr_pct,alpha,beta,sharpe_ratio,sortino_ratio,std_dev_ann_pct,max_drawdown_pct,aum_crore,expense_ratio_pct,morningstar_rating,risk_grade
0,119551,SBI Bluechip Fund - Regular Plan - Growth,SBI Mutual Fund,Large Cap,Regular,12.42,12.36,14.45,11.49,0.87,0.89,0.88,1.29,14.0,-21.70,14288,1.54,4,Moderate
1,119552,SBI Bluechip Fund - Direct Plan - Growth,SBI Mutual Fund,Large Cap,Direct,15.25,11.30,14.23,9.52,1.78,0.87,0.81,1.29,14.0,-24.43,1231,0.66,3,Moderate
2,119598,SBI Small Cap Fund - Regular Plan - Growth,SBI Mutual Fund,Small Cap,Regular,24.56,23.39,20.67,22.16,1.23,0.89,0.94,1.35,25.0,-13.35,19259,1.43,5,Very High
3,119599,SBI Small Cap Fund - Direct Plan - Growth,SBI Mutual Fund,Small Cap,Direct,20.59,23.14,21.82,22.01,1.13,1.04,0.93,1.67,25.0,-24.78,36061,0.72,4,Very High
4,119120,SBI Magnum Gilt Fund - Regular Plan - Growth,SBI Mutual Fund,Gilt,Regular,5.34,6.07,5.43,4.47,1.60,0.22,1.52,2.11,4.0,-2.30,24101,0.77,5,Low

In [49]:
performance.info()

<class 'pandas.DataFrame'>
RangeIndex: 40 entries, 0 to 39
Data columns (total 19 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   amfi_code           40 non-null     int64
 1   scheme_name         40 non-null     str
 2   fund_house          40 non-null     str
 3   category            40 non-null     str
 4   plan                40 non-null     str
 5   return_1yr_pct      40 non-null     float64
 6   return_3yr_pct      40 non-null     float64
 7   return_5yr_pct      40 non-null     float64
 8   benchmark_3yr_pct   40 non-null     float64
 9   alpha               40 non-null     float64
 10  beta                40 non-null     float64
 11  sharpe_ratio        40 non-null     float64
 12  sortino_ratio       40 non-null     float64
 13  std_dev_ann_pct     40 non-null     float64
 14  max_drawdown_pct    40 non-null     float64
 15  aum_crore           40 non-null     int64
 16  expense_ratio_pct   40 non-null     float64
 17  morningstar_rating  40 non-null     int64
 18  risk_grade          40 non-null     str
dtypes: float64(11), int64(3), str(5)
memory usage: 6.1 KB

In [50]:
performance.columns

Index(['amfi_code', 'scheme_name', 'fund_house', 'category', 'plan',
       'return_1yr_pct', 'return_3yr_pct', 'return_5yr_pct',
       'benchmark_3yr_pct', 'alpha', 'beta', 'sharpe_ratio', 'sortino_ratio',
       'std_dev_ann_pct', 'max_drawdown_pct', 'aum_crore', 'expense_ratio_pct',
       'morningstar_rating', 'risk_grade'],
      dtype='str')

In [51]:
#Missing_values
performance.isnull().sum()

amfi_code             0
scheme_name           0
fund_house            0
category              0
plan                  0
return_1yr_pct        0
return_3yr_pct        0
return_5yr_pct        0
benchmark_3yr_pct     0
alpha                 0
beta                  0
sharpe_ratio          0
sortino_ratio         0
std_dev_ann_pct       0
max_drawdown_pct      0
aum_crore             0
expense_ratio_pct     0
morningstar_rating    0
risk_grade            0
dtype: int64

In [52]:
#duplicate_values
performance.duplicated().sum()

np.int64(0)

In [53]:
#anamoulis
performance[
    performance['return_1yr_pct'] > 100
]

Empty DataFrame
Columns: [amfi_code, scheme_name, fund_house, category, plan, return_1yr_pct, return_3yr_pct, return_5yr_pct, benchmark_3yr_pct, alpha, beta, sharpe_ratio, sortino_ratio, std_dev_ann_pct, max_drawdown_pct, aum_crore, expense_ratio_pct, morningstar_rating, risk_grade]
Index: []

In [54]:
performance[
    performance['return_1yr_pct'] > 100
].shape

(0, 19)

In [55]:
performance[
    performance['return_3yr_pct'] > 100
]

Empty DataFrame
Columns: [amfi_code, scheme_name, fund_house, category, plan, return_1yr_pct, return_3yr_pct, return_5yr_pct, benchmark_3yr_pct, alpha, beta, sharpe_ratio, sortino_ratio, std_dev_ann_pct, max_drawdown_pct, aum_crore, expense_ratio_pct, morningstar_rating, risk_grade]
Index: []

In [56]:
performance[
    performance['return_3yr_pct'] > 100
].shape

(0, 19)

In [59]:
anomalies = performance[
    performance['return_5yr_pct'] > 100
]
print(anomalies)
anomalies.shape

Empty DataFrame
Columns: [amfi_code, scheme_name, fund_house, category, plan, return_1yr_pct, return_3yr_pct, return_5yr_pct, benchmark_3yr_pct, alpha, beta, sharpe_ratio, sortino_ratio, std_dev_ann_pct, max_drawdown_pct, aum_crore, expense_ratio_pct, morningstar_rating, risk_grade]
Index: []

(0, 19)

In [60]:
performance[
    ['return_1yr_pct',
     'return_3yr_pct',
     'return_5yr_pct']
].describe()

       return_1yr_pct  return_3yr_pct  return_5yr_pct
count       40.000000       40.000000       40.000000
mean        14.376000       14.089000       14.516750
std          4.883023        4.617253        4.454021
min          4.260000        5.140000        5.430000
25%         11.735000       12.035000       12.340000
50%         14.620000       14.205000       14.185000
75%         16.392500       15.882500       17.585000
max         24.930000       23.390000       23.800000

In [64]:
#checking for expense ratio
invalid_expense = performance[
    (performance['expense_ratio_pct'] < 0.1)
    |
    (performance['expense_ratio_pct'] > 2.5)
]
invalid_expense.shape

(0, 19)

In [65]:
#scheme_performance.csv dataset is cleaned
performance.to_csv(
    "../data/processed/scheme_performance_cleaned.csv",
    index=False
)

In [68]:
#Working on fund_master.csv dataset
fund_master = pd.read_csv("../data/raw/01_fund_master.csv")
print(fund_master.info())

<class 'pandas.DataFrame'>
RangeIndex: 40 entries, 0 to 39
Data columns (total 15 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   amfi_code           40 non-null     int64
 1   fund_house          40 non-null     str
 2   scheme_name         40 non-null     str
 3   category            40 non-null     str
 4   sub_category        40 non-null     str
 5   plan                40 non-null     str
 6   launch_date         40 non-null     str
 7   benchmark           40 non-null     str
 8   expense_ratio_pct   40 non-null     float64
 9   exit_load_pct       40 non-null     float64
 10  min_sip_amount      40 non-null     int64
 11  min_lumpsum_amount  40 non-null     int64
 12  fund_manager        40 non-null     str
 13  risk_category       40 non-null     str
 14  sebi_category_code  40 non-null     str
dtypes: float64(2), int64(3), str(10)
memory usage: 4.8 KB
None

In [67]:
#Checking Missing values and duplicates
print(fund_master.isnull().sum())
print("Duplicates:", fund_master.duplicated().sum())
fund_master = fund_master.drop_duplicates()

amfi_code             0
fund_house            0
scheme_name           0
category              0
sub_category          0
plan                  0
launch_date           0
benchmark             0
expense_ratio_pct     0
exit_load_pct         0
min_sip_amount        0
min_lumpsum_amount    0
fund_manager          0
risk_category         0
sebi_category_code    0
dtype: int64
Duplicates: 0

In [69]:
#fund_master.csv dataset is cleaned
fund_master.to_csv(
    "../data/processed/fund_master_cleaned.csv",
    index=False
)

In [70]:
#Working on fund_house.csv 
aum = pd.read_csv("../data/raw/03_aum_by_fund_house.csv")
print(aum.info())

<class 'pandas.DataFrame'>
RangeIndex: 90 entries, 0 to 89
Data columns (total 5 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   date            90 non-null     str
 1   fund_house      90 non-null     str
 2   aum_lakh_crore  90 non-null     float64
 3   aum_crore       90 non-null     int64
 4   num_schemes     90 non-null     int64
dtypes: float64(1), int64(2), str(2)
memory usage: 3.6 KB
None

In [71]:
#Checking for missing vaalues and duplicates
print(aum.isnull().sum())
print("Duplicates:", aum.duplicated().sum())
aum = aum.drop_duplicates()

date              0
fund_house        0
aum_lakh_crore    0
aum_crore         0
num_schemes       0
dtype: int64
Duplicates: 0

In [72]:
#fund_house.csv dataset is cleaned
aum.to_csv(
    "../data/processed/aum_by_fund_house_cleaned.csv",
    index=False
)

In [73]:
#Working on category_inflows.csv dataset
category = pd.read_csv("../data/raw/05_category_inflows.csv")
print(category.info())

<class 'pandas.DataFrame'>
RangeIndex: 144 entries, 0 to 143
Data columns (total 3 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   month             144 non-null    str
 1   category          144 non-null    str
 2   net_inflow_crore  144 non-null    float64
dtypes: float64(1), str(2)
memory usage: 3.5 KB
None

In [74]:
#checking for missing values and duplicates
print(category.isnull().sum())
print("Duplicates:", category.duplicated().sum())
category = category.drop_duplicates()

month               0
category            0
net_inflow_crore    0
dtype: int64
Duplicates: 0

In [75]:
#category_inflows.csv is cleaned.
category.to_csv(
    "../data/processed/category_inflows_cleaned.csv",
    index=False
)

In [76]:
#Working on industry_folio_count.csv dataset
folio = pd.read_csv("../data/raw/06_industry_folio_count.csv")
print(folio.info())

<class 'pandas.DataFrame'>
RangeIndex: 21 entries, 0 to 20
Data columns (total 6 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   month                21 non-null     str
 1   total_folios_crore   21 non-null     float64
 2   equity_folios_crore  21 non-null     float64
 3   debt_folios_crore    21 non-null     float64
 4   hybrid_folios_crore  21 non-null     float64
 5   others_folios_crore  21 non-null     float64
dtypes: float64(5), str(1)
memory usage: 1.1 KB
None

In [77]:
#Checking for missing values and duplicates
print(folio.isnull().sum())
print("Duplicates:", folio.duplicated().sum())
folio = folio.drop_duplicates()

month                  0
total_folios_crore     0
equity_folios_crore    0
debt_folios_crore      0
hybrid_folios_crore    0
others_folios_crore    0
dtype: int64
Duplicates: 0

In [78]:
#industry_folio_count.csv dataset is cleaned
folio.to_csv(
    "../data/processed/industry_folio_count_cleaned.csv",
    index=False
)

In [79]:
#Working on portfolio_holdings.csv dataset
holdings = pd.read_csv("../data/raw/09_portfolio_holdings.csv")
print(holdings.info())

<class 'pandas.DataFrame'>
RangeIndex: 322 entries, 0 to 321
Data columns (total 8 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   amfi_code          322 non-null    int64
 1   stock_symbol       322 non-null    str
 2   stock_name         322 non-null    str
 3   sector             322 non-null    str
 4   weight_pct         322 non-null    float64
 5   market_value_cr    322 non-null    float64
 6   current_price_inr  322 non-null    float64
 7   portfolio_date     322 non-null    str
dtypes: float64(3), int64(1), str(4)
memory usage: 20.3 KB
None

In [82]:
#Checking for missing and duplicate values
print(holdings.isnull().sum())
print("Duplicates:", holdings.duplicated().sum())
holdings = holdings.drop_duplicates()

amfi_code            0
stock_symbol         0
stock_name           0
sector               0
weight_pct           0
market_value_cr      0
current_price_inr    0
portfolio_date       0
dtype: int64
Duplicates: 0

In [83]:
#portfolio_holdings.csv dataset is cleaned
holdings.to_csv(
    "../data/processed/portfolio_holdings_cleaned.csv",
    index=False
)

In [84]:
#Working on benchmark_indices.csv dataset
benchmark = pd.read_csv("../data/raw/10_benchmark_indices.csv")
print(benchmark.info())

<class 'pandas.DataFrame'>
RangeIndex: 8050 entries, 0 to 8049
Data columns (total 3 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   date         8050 non-null   str
 1   index_name   8050 non-null   str
 2   close_value  8050 non-null   float64
dtypes: float64(1), str(2)
memory usage: 188.8 KB
None

In [86]:
#Checking for missing and duplicates values
print(benchmark.isnull().sum())
print("Duplicates:", benchmark.duplicated().sum())
benchmark = benchmark.drop_duplicates()

date           0
index_name     0
close_value    0
dtype: int64
Duplicates: 0

In [87]:
#benchmark_indices.csv dataset is cleaned
benchmark.to_csv(
    "../data/processed/benchmark_indices_cleaned.csv",
    index=False
)

In [140]:
#creating SQLite database
from sqlalchemy import create_engine
engine = create_engine("sqlite:///bluestock_mf.db")
print("Database created successfully")

Database created successfully

In [141]:
#loading fund_master dataset
import pandas as pd
fund_master = pd.read_csv(
    "../data/processed/fund_master_cleaned.csv"
)
fund_master.to_sql(
    "dim_fund",
    engine,
    if_exists="replace",
    index=False
)
print("Loaded dim_fund")

Loaded dim_fund

In [142]:
pd.read_sql(
    "SELECT COUNT(*) as rows FROM dim_fund",
    engine
)

   rows
0    40

In [143]:
fund_master = pd.read_csv("../data/processed/fund_master_cleaned.csv")
print(fund_master.columns)

Index(['amfi_code', 'fund_house', 'scheme_name', 'category', 'sub_category',
       'plan', 'launch_date', 'benchmark', 'expense_ratio_pct',
       'exit_load_pct', 'min_sip_amount', 'min_lumpsum_amount', 'fund_manager',
       'risk_category', 'sebi_category_code'],
      dtype='str')

In [144]:
nav = pd.read_csv("../data/processed/nav_history_cleaned.csv")
print(nav.columns)

Index(['amfi_code', 'date', 'nav'], dtype='str')

In [145]:
txn = pd.read_csv("../data/processed/investor_transactions_cleaned.csv")
print(txn.columns)

Index(['investor_id', 'transaction_date', 'amfi_code', 'transaction_type',
       'amount_inr', 'state', 'city', 'city_tier', 'age_group', 'gender',
       'annual_income_lakh', 'payment_mode', 'kyc_status'],
      dtype='str')

In [146]:
perf = pd.read_csv("../data/processed/scheme_performance_cleaned.csv")
print(perf.columns)

Index(['amfi_code', 'scheme_name', 'fund_house', 'category', 'plan',
       'return_1yr_pct', 'return_3yr_pct', 'return_5yr_pct',
       'benchmark_3yr_pct', 'alpha', 'beta', 'sharpe_ratio', 'sortino_ratio',
       'std_dev_ann_pct', 'max_drawdown_pct', 'aum_crore', 'expense_ratio_pct',
       'morningstar_rating', 'risk_grade'],
      dtype='str')

In [147]:
aum = pd.read_csv("../data/processed/aum_by_fund_house_cleaned.csv")
print(aum.columns)

Index(['date', 'fund_house', 'aum_lakh_crore', 'aum_crore', 'num_schemes'], dtype='str')

In [175]:
#creating schema
from sqlalchemy import create_engine, text
engine = create_engine("sqlite:///bluestock_mf.db")
with engine.connect() as conn:

    conn.execute(text("""
    CREATE TABLE IF NOT EXISTS dim_fund (
        amfi_code TEXT PRIMARY KEY,
        fund_house TEXT,
        scheme_name TEXT,
        category TEXT,
        sub_category TEXT,
        plan TEXT,
        launch_date DATE,
        benchmark TEXT,
        expense_ratio_pct REAL,
        exit_load_pct REAL,
        min_sip_amount REAL,
        min_lumpsum_amount REAL,
        fund_manager TEXT,
        risk_category TEXT,
        sebi_category_code TEXT
    )
    """))

    conn.execute(text("""
CREATE TABLE IF NOT EXISTS dim_date (
    date_id INTEGER PRIMARY KEY AUTOINCREMENT,
    date DATE,
    year INTEGER,
    quarter INTEGER,
    month INTEGER,
    day INTEGER
)
"""))

    conn.execute(text("""
    CREATE TABLE IF NOT EXISTS fact_nav (
        nav_id INTEGER PRIMARY KEY AUTOINCREMENT,
        amfi_code TEXT,
        date DATE,
        nav REAL,
        FOREIGN KEY (amfi_code)
            REFERENCES dim_fund(amfi_code)
    )
    """))

    conn.execute(text("""
    CREATE TABLE IF NOT EXISTS fact_transactions (
        transaction_id INTEGER PRIMARY KEY AUTOINCREMENT,
        investor_id TEXT,
        transaction_date DATE,
        amfi_code TEXT,
        transaction_type TEXT,
        amount_inr REAL,
        state TEXT,
        city TEXT,
        city_tier TEXT,
        age_group TEXT,
        gender TEXT,
        annual_income_lakh REAL,
        payment_mode TEXT,
        kyc_status TEXT,
        FOREIGN KEY (amfi_code)
            REFERENCES dim_fund(amfi_code)
    )
    """))

    conn.execute(text("""
    CREATE TABLE IF NOT EXISTS fact_performance (
        performance_id INTEGER PRIMARY KEY AUTOINCREMENT,
        amfi_code TEXT,
        return_1yr_pct REAL,
        return_3yr_pct REAL,
        return_5yr_pct REAL,
        benchmark_3yr_pct REAL,
        alpha REAL,
        beta REAL,
        sharpe_ratio REAL,
        sortino_ratio REAL,
        std_dev_ann_pct REAL,
        max_drawdown_pct REAL,
        aum_crore REAL,
        expense_ratio_pct REAL,
        morningstar_rating INTEGER,
        risk_grade TEXT,
        FOREIGN KEY (amfi_code)
            REFERENCES dim_fund(amfi_code)
    )
    """))

    conn.execute(text("""
    CREATE TABLE IF NOT EXISTS fact_aum (
        aum_id INTEGER PRIMARY KEY AUTOINCREMENT,
        date DATE,
        fund_house TEXT,
        aum_lakh_crore REAL,
        aum_crore REAL,
        num_schemes INTEGER
    )
    """))

    conn.commit()

print("All tables created successfully!")

All tables created successfully!

In [150]:
#loading the cleaned datasets into SQLite
#loading dim_fund
import pandas as pd
fund_master = pd.read_csv("../data/processed/fund_master_cleaned.csv")
fund_master.to_sql(
    "dim_fund",
    con=engine,
    if_exists="replace",
    index=False
)
print("dim_fund loaded")

dim_fund loaded

In [176]:
#loading dim_date
import pandas as pd
nav = pd.read_csv("../data/processed/nav_history_cleaned.csv")
dim_date = pd.DataFrame({
    "date": pd.to_datetime(nav["date"]).drop_duplicates()
})
dim_date["year"] = dim_date["date"].dt.year
dim_date["quarter"] = dim_date["date"].dt.quarter
dim_date["month"] = dim_date["date"].dt.month
dim_date["day"] = dim_date["date"].dt.day

dim_date.to_sql(
    "dim_date",
    con=engine,
    if_exists="replace",
    index=False
)
print("dim_date loaded")

dim_date loaded

In [151]:
#loading fact_nav
nav = pd.read_csv("../data/processed/nav_history_cleaned.csv")
nav.to_sql(
    "fact_nav",
    con=engine,
    if_exists="replace",
    index=False
)
print("fact_nav loaded")

fact_nav loaded

In [152]:
#loading fact_transactions
transactions = pd.read_csv(
    "../data/processed/investor_transactions_cleaned.csv"
)
transactions.to_sql(
    "fact_transactions",
    con=engine,
    if_exists="replace",
    index=False
)
print("fact_transactions loaded")

fact_transactions loaded

In [153]:
#loading fact_performance
performance = pd.read_csv(
    "../data/processed/scheme_performance_cleaned.csv"
)

performance.to_sql(
    "fact_performance",
    con=engine,
    if_exists="replace",
    index=False
)

print("fact_performance loaded")

fact_performance loaded

In [154]:
#loading fact_aum
aum = pd.read_csv(
    "../data/processed/aum_by_fund_house_cleaned.csv"
)
aum.to_sql(
    "fact_aum",
    con=engine,
    if_exists="replace",
    index=False
)
print("fact_aum loaded")

fact_aum loaded

In [157]:
#verifying row counts
pd.read_sql(
    "SELECT COUNT(*) AS rows FROM dim_fund",
    engine
)

   rows
0    40

In [177]:
pd.read_sql(
    "SELECT COUNT(*) AS rows FROM dim_date",
    engine
)

   rows
0  1150

In [158]:
pd.read_sql(
    "SELECT COUNT(*) AS rows FROM fact_nav",
    engine
)

    rows
0  46000

In [159]:
pd.read_sql(
    "SELECT COUNT(*) AS rows FROM fact_transactions",
    engine
)

    rows
0  32778

In [160]:
pd.read_sql(
    "SELECT COUNT(*) AS rows FROM fact_performance",
    engine
)

   rows
0    40

In [161]:
pd.read_sql(
    "SELECT COUNT(*) AS rows FROM fact_aum",
    engine
)

   rows
0    90

In [163]:
#Top 5 Fund Houses by AUM
import pandas as pd

query = """
SELECT fund_house,
       MAX(aum_crore) AS max_aum
FROM fact_aum
GROUP BY fund_house
ORDER BY max_aum DESC
LIMIT 5;
"""
result = pd.read_sql(query, engine)
print(result)

            fund_house  max_aum
0      SBI Mutual Fund  1250000
1  ICICI Prudential MF  1074000
2     HDFC Mutual Fund   930000
3      Nippon India MF   700000
4    Kotak Mahindra MF   580000

In [164]:
#Average nav
import pandas as pd

query = """
SELECT AVG(nav) AS avg_nav
FROM fact_nav;
"""
result = pd.read_sql(query, engine)
print(result)

      avg_nav
0  269.570265

In [165]:
#Total sip investment
pd.read_sql("""
SELECT SUM(amount_inr) AS total_sip_amount
FROM fact_transactions
WHERE transaction_type = 'SIP';
""", engine)

   total_sip_amount
0         217233491

In [166]:
#transactions by state
pd.read_sql("""
SELECT state,
       COUNT(*) AS total_transactions
FROM fact_transactions
GROUP BY state
ORDER BY total_transactions DESC;
""", engine)

             state  total_transactions
0           Punjab                2965
1   Madhya Pradesh                2931
2       Tamil Nadu                2806
3          Gujarat                2780
4      West Bengal                2748
5          Haryana                2736
6        Telangana                2718
7    Uttar Pradesh                2695
8            Delhi                2677
9        Karnataka                2621
10       Rajasthan                2577
11     Maharashtra                2524

In [167]:
#funds with expense ratio
pd.read_sql("""
SELECT scheme_name,
       expense_ratio_pct
FROM fact_performance
WHERE expense_ratio_pct < 1;
""", engine)

                                          scheme_name  expense_ratio_pct
0            SBI Bluechip Fund - Direct Plan - Growth               0.66
1           SBI Small Cap Fund - Direct Plan - Growth               0.72
2        SBI Magnum Gilt Fund - Regular Plan - Growth               0.77
3            HDFC Top 100 Fund - Direct Plan - Growth               0.92
4   HDFC Mid-Cap Opportunities Fund - Direct - Growth               0.78
5        HDFC Short Term Debt Fund - Regular - Growth               0.56
6           ICICI Pru Bluechip Fund - Direct - Growth               0.80
7            ICICI Pru Liquid Fund - Regular - Growth               0.74
8       Nippon India Large Cap Fund - Direct - Growth               0.72
9                      Nippon India ETF Nifty 50 BeES               0.89
10  Nippon India Gilt Securities Fund - Regular - ...               0.55
11               Kotak Liquid Fund - Regular - Growth               0.60
12               Axis Bluechip Fund - Direct - Growth               0.75
13                ABSL Liquid Fund - Regular - Growth               0.79

In [168]:
#Top 10 funds by 1-year return
pd.read_sql("""
SELECT scheme_name,
       return_1yr_pct
FROM fact_performance
ORDER BY return_1yr_pct DESC
LIMIT 10;
""", engine)

                                         scheme_name  return_1yr_pct
0             ABSL Small Cap Fund - Regular - Growth           24.93
1         SBI Small Cap Fund - Regular Plan - Growth           24.56
2             Axis Small Cap Fund - Regular - Growth           21.97
3     Nippon India Small Cap Fund - Regular - Growth           21.30
4          SBI Small Cap Fund - Direct Plan - Growth           20.59
5              DSP Small Cap Fund - Regular - Growth           20.20
6  HDFC Mid-Cap Opportunities Fund - Direct - Growth           19.98
7              UTI Flexi Cap Fund - Regular - Growth           17.43
8      Kotak Emerging Equity Fund - Regular - Growth           17.12
9  ICICI Pru Value Discovery Fund - Regular - Growth           16.67

In [169]:
#Top 10 funds in 5 year return
pd.read_sql("""
SELECT scheme_name,
       return_5yr_pct
FROM fact_performance
ORDER BY return_5yr_pct DESC
LIMIT 10;
""", engine)

                                         scheme_name  return_5yr_pct
0             ABSL Small Cap Fund - Regular - Growth           23.80
1             Axis Small Cap Fund - Regular - Growth           22.62
2     Nippon India Small Cap Fund - Regular - Growth           21.88
3          SBI Small Cap Fund - Direct Plan - Growth           21.82
4         SBI Small Cap Fund - Regular Plan - Growth           20.67
5              DSP Small Cap Fund - Regular - Growth           20.61
6                 DSP Midcap Fund - Regular - Growth           19.00
7                Axis Midcap Fund - Regular - Growth           18.94
8      Kotak Emerging Equity Fund - Regular - Growth           17.75
9  HDFC Mid-Cap Opportunities Fund - Regular - Gr...           17.69

In [170]:
#Average AUM by fund house
pd.read_sql("""
SELECT fund_house,
       AVG(aum_crore) AS avg_aum
FROM fact_aum
GROUP BY fund_house
ORDER BY avg_aum DESC;
""", engine)

                 fund_house        avg_aum
0           SBI Mutual Fund  943444.444444
1       ICICI Prudential MF  699222.222222
2          HDFC Mutual Fund  636888.888889
3           Nippon India MF  434333.333333
4         Kotak Mahindra MF  389111.111111
5  Aditya Birla Sun Life MF  341888.888889
6           UTI Mutual Fund  297888.888889
7          Axis Mutual Fund  280111.111111
8            Mirae Asset MF  173444.444444
9           DSP Mutual Fund  156555.555556

In [171]:
#total redemption amount
pd.read_sql("""
SELECT SUM(amount_inr) AS total_redemption
FROM fact_transactions
WHERE transaction_type = 'Redemption';
""", engine)

   total_redemption
0        1244525491

In [172]:
#Popular transaction type
pd.read_sql("""
SELECT transaction_type,
       COUNT(*) AS total_count
FROM fact_transactions
GROUP BY transaction_type
ORDER BY total_count DESC;
""", engine)

  transaction_type  total_count
0              SIP        19716
1          Lumpsum         8095
2       Redemption         4967

In [174]:
import pandas as pd
import os

processed_folder = "../data/processed"

for file in os.listdir(processed_folder):
    if file.endswith(".csv"):
        print("\n" + "="*60)
        print(file)

        df = pd.read_csv(os.path.join(processed_folder, file))

        print(df.columns.tolist())

============================================================
aum_by_fund_house_cleaned.csv
['date', 'fund_house', 'aum_lakh_crore', 'aum_crore', 'num_schemes']

============================================================
benchmark_indices_cleaned.csv
['date', 'index_name', 'close_value']

============================================================
category_inflows_cleaned.csv
['month', 'category', 'net_inflow_crore']

============================================================
fund_master_cleaned.csv
['amfi_code', 'fund_house', 'scheme_name', 'category', 'sub_category', 'plan', 'launch_date', 'benchmark', 'expense_ratio_pct', 'exit_load_pct', 'min_sip_amount', 'min_lumpsum_amount', 'fund_manager', 'risk_category', 'sebi_category_code']

============================================================
industry_folio_count_cleaned.csv
['month', 'total_folios_crore', 'equity_folios_crore', 'debt_folios_crore', 'hybrid_folios_crore', 'others_folios_crore']

============================================================
investor_transactions_cleaned.csv
['investor_id', 'transaction_date', 'amfi_code', 'transaction_type', 'amount_inr', 'state', 'city', 'city_tier', 'age_group', 'gender', 'annual_income_lakh', 'payment_mode', 'kyc_status']

============================================================
nav_history_cleaned.csv
['amfi_code', 'date', 'nav']

============================================================
portfolio_holdings_cleaned.csv
['amfi_code', 'stock_symbol', 'stock_name', 'sector', 'weight_pct', 'market_value_cr', 'current_price_inr', 'portfolio_date']

============================================================
scheme_performance_cleaned.csv
['amfi_code', 'scheme_name', 'fund_house', 'category', 'plan', 'return_1yr_pct', 'return_3yr_pct', 'return_5yr_pct', 'benchmark_3yr_pct', 'alpha', 'beta', 'sharpe_ratio', 'sortino_ratio', 'std_dev_ann_pct', 'max_drawdown_pct', 'aum_crore', 'expense_ratio_pct', 'morningstar_rating', 'risk_grade']